/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Make_sale;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author KEVO
 */
public class All_sales extends javax.swing.JFrame {

    /**
     * Creates new form All_sales
     */
    public void All_sales_totals(){
         try {
            int sum=0;
            int sum2=0;
        for(int i=0;i<All_sale_table.getRowCount();i++){
            sum=sum+Integer.parseInt(All_sale_table.getValueAt(i,3).toString());
            sum2=sum2+Integer.parseInt(All_sale_table.getValueAt(i,4).toString());
            Selling_price.setText(Integer.toString(sum));
            Buying_price.setText(Integer.toString(sum2));
            int margin=sum-sum2;
            Margins.setText(Integer.toString(margin));

        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"An error occured please Contact 0722208086");
        }
         
    }
    public void loading(){
        try {
             String query="SELECT * FROM sold";
                                        
                                        
					PreparedStatement ps=null;
					ResultSet rs=null;
					ps=con.prepareStatement(query);
					rs=ps.executeQuery();
                                        All_sale_table.setModel(DbUtils.resultSetToTableModel(rs));
                                        All_sales_totals();
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
  Connection con=null;  
    
    
    public All_sales() {
        initComponents();
        con=DB_CONNECT.db_connection.db_con();
        loading();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        All_sale_table = new javax.swing.JTable();
        Selling_price = new javax.swing.JTextField();
        Buying_price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Margins = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        All_sale_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        All_sale_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        All_sale_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM NAME", "SIZE", "SELLING PRICE", "BUYING PRICE", "STOCK QUANTITY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(All_sale_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, 930, 340));

        Selling_price.setBackground(new java.awt.Color(0, 0, 0));
        Selling_price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Selling_price.setForeground(new java.awt.Color(0, 255, 102));
        Selling_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Selling_priceActionPerformed(evt);
            }
        });
        getContentPane().add(Selling_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 90, -1));

        Buying_price.setBackground(new java.awt.Color(0, 0, 0));
        Buying_price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Buying_price.setForeground(new java.awt.Color(0, 255, 102));
        getContentPane().add(Buying_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("TOTAL ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 66, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("TOTAL ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 360, 80, -1));

        Margins.setBackground(new java.awt.Color(0, 0, 0));
        Margins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Margins.setForeground(new java.awt.Color(0, 255, 102));
        getContentPane().add(Margins, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("MARGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 452, 83, 30));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Selling_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Selling_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Selling_priceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_sales().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable All_sale_table;
    private javax.swing.JTextField Buying_price;
    private javax.swing.JTextField Margins;
    private javax.swing.JTextField Selling_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
